---
openapi: 3.0.0
info:
  title: API for Super Admin in CMS
  description: CMS-Super Admin
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: /
tags:
- name: Super Administrator
  description: Secured Super Admin-only calls
paths:
  /retrieve_logs:
    get:
      tags:
      - Super Administrator
      summary: Retrieve Logs
      description: |
        By passing in the appropriate options, you can search for
        available logs in the system
      operationId: retrieveLogs
      parameters:
      - name: logType
        in: query
        description: Type of logs to be retrieved
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: hospital_id
        in: query
        description: retrieve logs by hospital ID
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: limit
        in: query
        description: maximum number of records to return
        required: false
        style: form
        explode: true
        schema:
          maximum: 50
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: search results matching criteria
        "400":
          description: bad input parameter
  /add_hospital_instance:
    post:
      tags:
      - Super Administrator
      summary: adds a hospital
      description: Adds an item to the system
      operationId: addHospital
      parameters:
      - name: Hospital Name
        in: query
        description: Hospital name
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: Admin Name
        in: query
        description: name of Administrator
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: Admin phone
        in: query
        description: Phone of Administrator
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "201":
          description: Hospital created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
  /delete_hospital_instance:
    delete:
      tags:
      - Super Administrator
      summary: Delete Hospital
      description: Deletes hospital instance
      operationId: delHospital
      parameters:
      - name: Hospital ID
        in: query
        description: ID of Hospital
        required: false
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "201":
          description: item deleted
        "400":
          description: invalid input, object invalid
  /add_category:
    post:
      tags:
      - Super Administrator
      summary: Add Medical Category
      description: Adds Category
      operationId: addCategory
      parameters:
      - name: category_name
        in: query
        description: Category name
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "201":
          description: item added
        "400":
          description: invalid input, object invalid
  /delete_category:
    delete:
      tags:
      - Super Administrator
      summary: Delete Medical Category
      description: Deletes Category
      operationId: delCategory
      parameters:
      - name: category_name
        in: query
        description: Category name
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "201":
          description: item deleted
        "400":
          description: invalid input, object invalid
components: {}
