export const constants = {
  // Labels to be shown
  REACT_APP_NAV_BRAND: "CMS",
  REACT_APP_SIDEBAR_SEARCH_PATIENT_DATA: "Search Patient Data",
  REACT_APP_SIDEBAR_REQUEST_CONSENT: "Request Consent",
  REACT_APP_SIDEBAR_HISTORY: "History",
  REACT_APP_SIDEBAR_VIEW_DATA: "View Data",
  REACT_APP_SIDEBAR_SHARED_CONSENTS: "Shared Consents",
  REACT_APP_SIDEBAR_RECENT_CONSENTS: "Recent Consents",
  REACT_APP_SIDEBAR_EMERGENCY_BUTTON_TEXT: "Emergency Consent",

  REACT_APP_SIDEBAR_PENDING_CONSENT_REQUEST: "Pending Consent Request",
  REACT_APP_SIDEBAR_PATIENT_ONGOING_CONSENT: "Patient Ongoing Consent",
  REACT_APP_SIDEBAR_PAST_CONSENT_REQUEST: "Past Consent Request",
  REACT_APP_SIDEBAR_GET_MY_RECORDS: "Get My Records",

  REACT_APP_REGISTRATION_HEADING: "Registration",
  REACT_APP_NAME_LABEL: "Name",
  REACT_APP_EMAIL_LABEL: "Email",
  REACT_APP_PHONE_NO_LABEL: "Phone No",
  REACT_APP_GENDER_LABEL: "Gender",
  REACT_APP_ADDRESS_LABEL: "Address",
  REACT_APP_ABHA_ID_LABEL: "ABHA ID",
  REACT_APP_REGISTER_LABEL: "Register",
  REACT_APP_SUCCESS_LABEL: "Success",
  REACT_APP_CLOSE_LABEL: "Close",

  // Image names
  REACT_APP_NAV_LOGOUT_IMG: "logout",
  REACT_APP_NAV_SETTINGS_IMG: "settings",
  REACT_APP_SIDEBAR_HISTORY_IMG: "history",
  REACT_APP_SIDEBAR_LENS_IMG: "lens",
  REACT_APP_SIDEBAR_SEND_IMG: "send",
  REACT_APP_SIDEBAR_SHARED_CONSENT_IMG: "shared_consent",
  REACT_APP_SIDEBAR_VIEW_DATA_IMG: "view_data",
  REACT_APP_SIDEBAR_WARNING_IMG: "warning",
  REACT_APP_SIDEBAR_RECENT_CONSENTS_IMG: "recent_consents",
  REACT_APP_SUCCESS_IMG: "success",

  REACT_APP_CREATE_HOSPITAL_HEADING_LABEL: "Add Hospital Instance",
  REACT_APP_CURRENT_HOSPITAL_LABEL: "Current Hospitals",
  REACT_APP_HOSPITAL_DROPDOWN_LABEL: "Hospitals (By ID)",
  REACT_APP_HOSPITAL_NAME_LABEL: "Hospital Name",
  REACT_APP_ADMIN_NAME_LABEL: "Administrator Name",
  REACT_APP_ADMIN_EMAIL_LABEL: "Administrator Email",
  REACT_APP_ADMIN_PHONE_LABEL: "Administrator Phone",
  REACT_APP_CREATE_HOSPITAL_LABEL: "Add Hospital",
  hospitalList: {
    0: "Select Hospital",
    1: "vivek",
    2: "Vitals",
    3: "Health",
    4: "Medicine",
    5: "Pharmacy",
  },
  recordTypes: {
    0: "Select Record Type",
    1: "Blood Report",
    2: "X-ray",
    3: "MRI Scanning",
    4: "General Observations",
    5: "Medicines",
  },
};
